FROM rockylinux

RUN dnf upgrade -y && \
    dnf install -y \
        autoconf \
        automake \
        bzip2 \
        bzip2-devel \
        cmake \
        freetype-devel \
        gcc \
        gcc-c++ \
        git \
        libtool \
        make \
        pkgconfig \
        python3 \
        tree \ 
        zlib-devel

RUN mkdir /ffmpeg_sources && \
    cd /ffmpeg_sources && \
    curl -O -L https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2 && \
    tar xjvf nasm-2.15.05.tar.bz2 && \
    cd nasm-2.15.05 && \
    ./autogen.sh && \
    ./configure --prefix="/ffmpeg_build" --bindir="/bin"&& \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    curl -O -L https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz && \
    tar xzvf yasm-1.3.0.tar.gz && \
    cd yasm-1.3.0 && \
    ./configure --prefix="/ffmpeg_build" --bindir="/bin" && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    git clone --branch stable --depth 1 https://code.videolan.org/videolan/x264.git && \
    cd x264 && \
    PKG_CONFIG_PATH="/ffmpeg_build/lib/pkgconfig" ./configure --prefix="/ffmpeg_build" --bindir="/bin" --enable-static && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    git clone --branch stable --depth 2 https://bitbucket.org/multicoreware/x265_git && \
    cd /ffmpeg_sources/x265_git/build/linux && \
    cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/ffmpeg_build" -DENABLE_SHARED:bool=off ../../source && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
    cd fdk-aac && \
    autoreconf -fiv && \
    ./configure --prefix="/ffmpeg_build" --disable-shared && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    curl -O -L https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz && \
    tar xzvf lame-3.100.tar.gz && \
    cd lame-3.100 && \
    ./configure --prefix="/ffmpeg_build" --bindir="/bin" --disable-shared --enable-nasm && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    curl -O -L https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz && \
    tar xzvf opus-1.3.1.tar.gz && \
    cd opus-1.3.1 && \
    ./configure --prefix="/ffmpeg_build" --disable-shared && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    git clone --depth 1 https://chromium.googlesource.com/webm/libvpx.git && \
    cd libvpx && \
    ./configure --prefix="/ffmpeg_build" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm && \
    make -j 16 && \
    make install

RUN cd /ffmpeg_sources && \
    curl -O -L https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
    tar xjvf ffmpeg-snapshot.tar.bz2 && \
    cd ffmpeg && \
    PATH="/bin" PKG_CONFIG_PATH="/ffmpeg_build/lib/pkgconfig" ./configure \
    --prefix="/ffmpeg_build" \
    --pkg-config-flags="--static" \
    --extra-cflags="-I/ffmpeg_build/include" \
    --extra-ldflags="-L/ffmpeg_build/lib" \
    --extra-libs=-lpthread \
    --extra-libs=-lm \
    --bindir="/bin" \
    --enable-gpl \
    --enable-libfdk_aac \
    --enable-libfreetype \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-nonfree && \
    make -j 16 && \
    make install

COPY ./shuffle_content.py /temp/shuffle_content.py

ENV STREAM_ADDRESS "rtmp://address:port/live/stream_key"

CMD python3 /temp/shuffle_content.py