FROM rockylinux

RUN dnf upgrade -y && \
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf install -y https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm && \
    dnf install -y https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm && \
    dnf install -y dnf-plugins-core && \
    dnf upgrade -y && \
    dnf install -y ffmpeg

RUN /bin/ffmpeg -version