# rockylinux base image
FROM hluengas/rocky_ffmpeg:latest

# set environment variables
ENV STREAM_ADDRESS "rtmp://address:port/live/stream_key"
ENV EPISODE_DIR "/tmp/content/episodes"
ENV BUMPER_DIR "/tmp/content/bumpers"
ENV META_DIR "/tmp/content/meta"
ENV VIDEO_ENCODER_PRESET "veryfast"
ENV UID "99"
ENV GID "100"

# add repos, upgrade packages, add python and tree
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf upgrade -y && \
    dnf install -y \
    python3 \
    tree

# Copy Scripts
COPY ./downtime_streamer.py /tmp/meta/downtime_streamer.py.py
COPY ./constants.py /tmp/meta/constants.py

# Change User
USER ${UID}:${GID}

# Entrypoint
CMD ["python3", "-u", "/tmp/meta/downtime_streamer.py"]